services:
  django:
    port: 8000
    image: reploy/python3:v1
    environment:
      DEBUG: true
    commands: 
      - pip3 -q install -r requirements.txt
      - printenv
      - python3 manage.py runserver 0.0.0.0:8000
