services:
  django:
    port: 8000
    runtime: python3
    environment:
      DEBUG: true
    build: 
      - pip3 -q install -r requirements.txt
      - pip3 show Django
    serve:
      - pip3 show Django
      - python3 manage.py runserver 0.0.0.0:8000
