services:
  django:
    port: 8000
    image: reploy/python3:v1
    environment:
      DEBUG: true
    serve: 
      - pip3 install -r requirements.txt
      - python3 manage.py runserver 0.0.0.0:8000
