services:
  django:
    port: 8000
    runtime: python3
    environment:
      DEBUG: true
    build: 
      - which tee
      - which pip3
      - pip3 -q install -r requirements.txt
    serve:
      - pip3 show Django
      - python3 manage.py runserver 0.0.0.0:8000
