services:
  django:
    port: 8000
    image: reploy/python3:v1
    environment:
      DEBUG: true
    serve: 
      - pip3 -q install -r requirements.txt
      - pip3 list -v
      - pip3 show Django
      - python3 manage.py runserver 0.0.0.0:8000
