services:
  django:
    port: 8000
    image: reploy/python3:v1
    environment:
      DEBUG: true
    commands: 
      - pip -q install -r requirements.txt
      - python manage.py runserver 0.0.0.0:8000
